[frontend]
10.20.2.4 ansible_user=azureuser

[backend]
10.20.3.4 ansible_user=azureuser

[sonarqube]
10.20.5.6 ansible_user=azureuser

[all:vars]
ansible_ssh_private_key_file=~/group4
ansible_python_interpreter=/usr/bin/python3

db_host=sqlgroup4b1pdu.database.windows.net
db_port=1433
db_name=appdb-group4b-1pdu
db_username=sqladminuser
db_password="ChangeMe456!"
app_gateway_url=http://20.205.212.128
repo_root=/home/azureuser/devops-project2-ih
backend_jar_path=/home/azureuser/devops-project2-ih/backend/target/burger-builder-backend-1.0.0.jar
frontend_dist_path=/home/azureuser/devops-project2-ih/frontend/dist/

